sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cclawrence/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true cclawrence/docker-react npm run test
