sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cclawrence/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true cclawrence/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "chelsiel-docker-react-2"
  env: "ChelsielDockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-157985778333"
  bucket_path: "chelsiel-docker-react-2"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
