sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cclawrence/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true cclawrence/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: ""
  app: ""
  env: ""
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
